config/routes.rb
Rails.application.routes.draw do
  resources :accounts
  resources :ads
  match "/scrapping" => "visitors#scrapping", via: [ :post, :get ]
  match "/destroy_all" => "visitors#destroy_all", via: [ :post, :get ]
  post 'ads/today_csv' => "ads#today_csv"
  post '/export_with_date' => 'ads#export_with_date'
  root to: 'visitors#index'

  
end

app/models/account.rb
class Account < ActiveRecord::Base
end

app/models/ad.rb
class Ad < ActiveRecord::Base
  validates :contact, uniqueness: true

  def self.as_csv
    col_names = 'contact'
    col_names = col_names.split(",") if  col_names.is_a?(String)
    CSV.generate(:col_sep => ",") do |csv|
      csv << col_names
      all.each do |item|
        csv << col_names.collect{|name| item.send(name).squish()}
      end
    end
  end

  def self.random_desktop_user_agent
    user_agents = [
      #'Windows IE 6',
      #'Windows IE 7',
      'Windows Mozilla',
      'Mac Safari',
      'Mac FireFox',
      'Mac Mozilla',
      'Linux Mozilla',
      'Linux Firefox',
      'Linux Konqueror',
      'iPhone']
   return user_agents.sample
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to :back, notice: 'Account was successfully saved.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :back, notice: "Failed to save account, please try again."}
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:username, :password)
    end
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  before_action :set_ad, only: [:show, :edit, :update, :destroy]

  # GET /ads
  # GET /ads.json
  def index
    @ads = Ad.all
    respond_to do |format|
      format.html
      format.csv { render text: @ads.as_csv }
    end
  end

  def today_csv
     @ads = Ad.where("created_at >= ?", Time.zone.now.beginning_of_day) 
     respond_to do |format|
      format.html
      format.csv { render text: @ads.as_csv }
    end
  end

  def export_with_date

  end

  # GET /ads/1
  # GET /ads/1.json
  def show
  end

  # GET /ads/new
  def new
    @ad = Ad.new
  end

  # GET /ads/1/edit
  def edit
  end

  # POST /ads
  # POST /ads.json
  def create
    @ad = Ad.new(ad_params)

    respond_to do |format|
      if @ad.save
        format.html { redirect_to @ad, notice: 'Ad was successfully created.' }
        format.json { render :show, status: :created, location: @ad }
      else
        format.html { render :new }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ads/1
  # PATCH/PUT /ads/1.json
  def update
    respond_to do |format|
      if @ad.update(ad_params)
        format.html { redirect_to @ad, notice: 'Ad was successfully updated.' }
        format.json { render :show, status: :ok, location: @ad }
      else
        format.html { render :edit }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ads/1
  # DELETE /ads/1.json
  def destroy
    @ad.destroy
    respond_to do |format|
      format.html { redirect_to ads_url, notice: 'Ad was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ad
      @ad = Ad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ad_params
      params.require(:ad).permit(:contact, :ad_id, :link)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def scrapping
    if params[:status] == "1"
      logger.info "inside 1"
      @pid = fork do
        exec "bundle exec rake contacts:from_ebayk"
      end
      logger.info @pid
      @status = @pid
      message = "started"
    else
      logger.info "inside 2"
      if params[:pid]
        logger.info "inside pi"
        begin
          @status = Process.kill "TERM", params[:pid].to_i
        rescue => e
          puts e
          @status = "failed"
        end
        logger.info @status
        message = "stopped"
      end
    end
    respond_to do |format|
      if @status
        format.html { redirect_to root_path(:pid => @pid), notice: "Scrapping #{message} now." }
      else
        format.html { redirect_to :back, notice: 'Failed to scrap, please try again.' }
      end
    end
  end

  def destroy_all
    Ad.destroy_all
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Destroyed all contacts. I am ready for a fresh start.' }
    end
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/_form.html.slim
= simple_form_for(@account) do |f|
  = f.error_notification

  .form-inputs
    = f.input :username
    = f.input :password

  .form-actions
    = f.button :submit

app/views/accounts/edit.html.slim
h1 Editing account

== render 'form'

= link_to 'Show', @account
'|
= link_to 'Back', accounts_path

app/views/accounts/index.html.slim
h1 Listing accounts

table
  thead
    tr
      th Username
      th Password
      th
      th
      th

  tbody
    - @accounts.each do |account|
      tr
        td = account.username
        td = account.password
        td = link_to 'Show', account
        td = link_to 'Edit', edit_account_path(account)
        td = link_to 'Destroy', account, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Account', new_account_path

app/views/accounts/new.html.slim
h1 New account

== render 'form'

= link_to 'Back', accounts_path

app/views/accounts/show.html.slim
p#notice = notice

p
  strong Username:
  = @account.username
p
  strong Password:
  = @account.password

= link_to 'Edit', edit_account_path(@account)
'|
= link_to 'Back', accounts_path

app/views/ads/_form.html.slim
= simple_form_for(@ad) do |f|
  = f.error_notification

  .form-inputs
    = f.input :contact
    = f.input :ad_id
    = f.input :link

  .form-actions
    = f.button :submit

app/views/ads/edit.html.slim
h1 Editing ad

== render 'form'

= link_to 'Show', @ad
'|
= link_to 'Back', ads_path

app/views/ads/index.html.slim
h1
  Contacts Gathered
  = link_to "Download as CSV", "/ads.csv", :class => "pull-right btn btn-success white", :id => "download-button"

table.table.table-bordered
  thead
    tr
      th Ad
      th Contact

  tbody
    - @ads.each do |ad|
      tr
        td
          = link_to ad.ad_id, ad.link
        td = ad.contact

app/views/ads/new.html.slim
h1 New ad

== render 'form'

= link_to 'Back', ads_path

app/views/ads/show.html.slim
p#notice = notice

p
  strong Contact:
  = @ad.contact
p
  strong Ad:
  = @ad.ad_id
p
  strong Link:
  = @ad.link

= link_to 'Edit', edit_ad_path(@ad)
'|
= link_to 'Back', ads_path

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        == render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li role="presentation">
  <%= link_to "Contacts", ads_path %>
</li>

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Ebayk'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Ebayk'}"
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => true
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    main[role="main"]
      div.container
        == render 'layouts/messages'
        == yield

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/visitors/index.html.slim
center
  h2 Ebay Kleinanzeigen Scrapper
  hr
  div.row
    div.col-md-6
      div.panel.panel-default
        div.panel-heading
          | Account in use
        div.panel-body
          div.input-group.input-group-sm.col-md-6
            span.input-group-addon
              | Username
            input.form-control disabled=true value=Account.last.username.to_s

          div.input-group.input-group-sm.col-md-6
            span.input-group-addon
              | Password
            input.form-control disabled=true value=Account.last.password.to_s.gsub(/([^@])[^@]/, '\1@')
    div.col-md-6
      div.panel.panel-primary
        div.panel-heading
          | Initiate Scrapping
        div.panel-body
          - if params[:pid]
            = button_to "Stop #{params[:pid]}", { :controller => "visitors", :action => "scrapping", :status => 2, :pid => params[:pid] }, :class => "btn btn-warning btn-lg", :id => "start-button", :data => { :confirm => "If the process #{params[:pid]} still running, do you still want to stop it?", :disable_with => "Stopping.." }
          - else
            = button_to "Start", { :controller => "visitors", :action => "scrapping", :status => 1 }, :class => "btn btn-success btn-lg", :id => "start-button", :data => { :disable_with => "Starting..", :remote => true, :method => :post }


hr
br
br

h3
  span.glyphicon.glyphicon-cog aria-hidden="true"
  |  Configurations
hr
br
div.col-md-6
  div.panel.panel-default
    div.panel-heading
      h4 kleinanzeigen.ebay.de Login
    div.panel-body
      = simple_form_for("account", :url => "/accounts") do |f|
          = f.input :username, :required => true
          = f.input :password, :required => true
          = f.submit "Save", :class => "btn btn-default"

div.col-md-6
  div.panel.panel-default
    div.panel-heading
      h4 Export Details
    div.panel-body
      = simple_form_for("export-details", :url => "/export_with_date",:html => { :class => "form-inline" }) do |f|
          = f.input :from_date, :placeholder => "From Date",:class => 'datepicker', :label => false
          = f.input :to_date, :placeholder => "To Date", :class => 'datepicker', :label => false
          = f.submit "Export", :class => "btn btn-default"
      hr
      = button_to "Export Today's Results", {:controller => "ads", :action => "today_csv", :format => :csv, :ad => {} }, :class => "btn btn-info pull-left", :id => "export-today-button", :data => { :loading_text => "Scrapping..." }
      = button_to "Export All", {:controller => "ads", :action => "index", :format => :csv, :ad => {} }, :class => "btn btn-info pull-left", :id => "export-all-button", :data => { :loading_text => "Scrapping...", disable_with: 'loading...'  }, :method => :get
      br
      br
      hr
      h3
        = button_to "Destroy Everything", "/destroy_all", :class => "btn btn-danger pull-right", :id => "destroy-button", :data => { :disable_with => "Destroying..." }
        | Clear everything scrapped so far.